import { Navbar } from '@/components/Navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'styles'

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${interSans.className} bg-[#f5f5f7] tracking-tight antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
